export const REQUEST_FETCH_LIST_TODOS = "REQUEST_FETCH_LIST_TODOS";
export const UPDATE_LIST_TODOS = "UPDATE_LIST_TODOS";

export const REQUEST_ADD_TODO = "REQUEST_ADD_TODO";
export const ADD_TODO = "ADD_TODO";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE";

export const COMPLETE_TODO = "COMPLETE_TODO";
export const INCOMPLETE_TODO = "INCOMPLETE_TODO";

export const EDIT_TITLE_TODO = "EDIT_TITLE_TODO";
export const SAVE_TODO = "SAVE_TODO";

export const REQUEST_REMOVE_TODO = "REQUEST_REMOVE_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const REMOVE_TODO_SUCCESS = "REMOVE_TODO_SUCCESS";
export const REMOVE_TODO_FAILURE = "REMOVE_TODO_FAILURE";

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_CHECK_STARTUP = "AUTH_CHECK_STARTUP";
export const AUTH_VERIFY_CALLBACK = "AUTH_VERIFY_CALLBACK";
export const AUTH_VERIFY_CALLBACK_SUCCESS = "AUTH_VERIFY_CALLBACK_SUCCESS";
export const AUTH_VERIFY_CALLBACK_FAILURE = "AUTH_VERIFY_CALLBACK_FAILURE";
export const AUTH_VERIFY_SET_DATA = "AUTH_VERIFY_SET_DATA";

export const AUTH_GET_PROFILE = "AUTH_GET_PROFILE";
export const AUTH_GET_PROFILE_SUCCESS = "AUTH_GET_PROFILE_SUCCESS";
export const AUTH_GET_PROFILE_FAILURE = "AUTH_GET_PROFILE_FAILURE";

