export const UPDATE_LIST_TODOS = "UPDATE_LIST_TODOS";

export const REQUEST_ADD_TODO = "REQUEST_ADD_TODO";
export const ADD_TODO = "ADD_TODO";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE";

export const COMPLETE_TODO = "COMPLETE_TODO";
export const INCOMPLETE_TODO = "INCOMPLETE_TODO";

export const EDIT_TITLE_TODO = "EDIT_TITLE_TODO";
export const SAVE_TODO = "SAVE_TODO";

export const REQUEST_REMOVE_TODO = "REQUEST_REMOVE_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const REMOVE_TODO_SUCCESS = "REMOVE_TODO_SUCCESS";
export const REMOVE_TODO_FAILURE = "REMOVE_TODO_FAILURE";

